/*
# Create Core Database Schema for Cybercrime Digital Evidence Analyzer

## Overview
This migration creates the complete database schema for a digital forensics
investigation platform. It includes 7 core tables plus a profiles table
linked to Supabase auth, with full relationships, constraints, indexes,
and Row-Level Security policies.

## New Tables

1. **profiles** — Extended user data linked to auth.users. Stores name and role
   (ADMIN, INVESTIGATOR, VIEWER). Auto-created via trigger on signup.

2. **cases** — Investigation cases. Each case has a unique case number
   (CASE-YYYY-NNN), name, description, status, and risk level.

3. **evidence** — Uploaded evidence files. Stores filename, file type, size,
   SHA-256 hash, storage path, and integrity status.

4. **events** — Normalized events extracted from evidence. Each event has a
   timestamp, type, username, source/destination IP, severity, and raw data.

5. **alerts** — Generated by the detection engine. Each alert references a
   case and has a type, severity, confidence score, reason, and detection rule.

6. **indicators** — Extracted indicators of compromise (IPs, usernames,
   filenames, domains, URLs, hashes) with occurrence counts and risk scores.

7. **audit_logs** — Records all significant user actions for chain of custody.

## Security
- RLS enabled on ALL tables
- Owner-scoped policies using auth.uid() for cases, evidence, events, alerts,
  indicators, and audit_logs
- Profiles are readable by the owner and writable by the owner (except role,
  which is only set at creation)
- All policies use TO authenticated with proper ownership checks

## Important Notes
1. The profiles table is auto-populated by a trigger when a new auth user is created.
2. The role is stored in raw_user_meta_data at signup and copied to profiles.
3. Case numbers are generated by the application as CASE-YYYY-NNN format.
4. Evidence SHA-256 hashes are computed client-side using the Web Crypto API.
5. All foreign keys use ON DELETE CASCADE to maintain referential integrity.
*/

-- ============================================================
-- PROFILES TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  name text NOT NULL DEFAULT '',
  email text NOT NULL,
  role text NOT NULL DEFAULT 'VIEWER' CHECK (role IN ('ADMIN', 'INVESTIGATOR', 'VIEWER')),
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

-- Profiles: users can read their own profile
DROP POLICY IF EXISTS "select_own_profile" ON profiles;
CREATE POLICY "select_own_profile" ON profiles FOR SELECT
  TO authenticated USING (auth.uid() = id);

-- Profiles: users can update their own profile (name only, not role)
DROP POLICY IF EXISTS "update_own_profile" ON profiles;
CREATE POLICY "update_own_profile" ON profiles FOR UPDATE
  TO authenticated USING (auth.uid() = id) WITH CHECK (auth.uid() = id);

-- Profiles: admins can read all profiles (for user management)
DROP POLICY IF EXISTS "admin_select_all_profiles" ON profiles;
CREATE POLICY "admin_select_all_profiles" ON profiles FOR SELECT
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'ADMIN')
  );

-- ============================================================
-- AUTO-CREATE PROFILE ON SIGNUP
-- Trigger function that creates a profiles row when a new auth.users row is inserted.
-- The role is read from raw_user_meta_data (set during signUp).
-- ============================================================
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, email, name, role)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'name', ''),
    COALESCE(NEW.raw_user_meta_data->>'role', 'INVESTIGATOR')
  );
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ============================================================
-- CASES TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS cases (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  case_number text NOT NULL UNIQUE,
  name text NOT NULL,
  description text,
  status text NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN', 'UNDER_INVESTIGATION', 'CLOSED', 'ARCHIVED')),
  risk_level text CHECK (risk_level IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
  created_by uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE cases ENABLE ROW LEVEL SECURITY;

-- Cases: authenticated users can see all cases (investigation team needs visibility)
DROP POLICY IF EXISTS "select_cases" ON cases;
CREATE POLICY "select_cases" ON cases FOR SELECT
  TO authenticated USING (true);

-- Cases: admins and investigators can create cases
DROP POLICY IF EXISTS "insert_cases" ON cases;
CREATE POLICY "insert_cases" ON cases FOR INSERT
  TO authenticated WITH CHECK (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role IN ('ADMIN', 'INVESTIGATOR'))
  );

-- Cases: admins and investigators can update cases
DROP POLICY IF EXISTS "update_cases" ON cases;
CREATE POLICY "update_cases" ON cases FOR UPDATE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role IN ('ADMIN', 'INVESTIGATOR'))
  ) WITH CHECK (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role IN ('ADMIN', 'INVESTIGATOR'))
  );

-- Cases: only admins can delete cases
DROP POLICY IF EXISTS "delete_cases" ON cases;
CREATE POLICY "delete_cases" ON cases FOR DELETE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'ADMIN')
  );

-- ============================================================
-- EVIDENCE TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS evidence (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  case_id uuid NOT NULL REFERENCES cases(id) ON DELETE CASCADE,
  filename text NOT NULL,
  original_filename text NOT NULL,
  file_type text NOT NULL,
  file_size bigint NOT NULL,
  sha256_hash text NOT NULL,
  storage_path text NOT NULL,
  uploaded_by uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  uploaded_at timestamptz NOT NULL DEFAULT now(),
  integrity_status text NOT NULL DEFAULT 'VERIFIED' CHECK (integrity_status IN ('VERIFIED', 'COMPROMISED', 'PENDING')),
  parsed boolean NOT NULL DEFAULT false
);

ALTER TABLE evidence ENABLE ROW LEVEL SECURITY;

-- Evidence: authenticated users can see all evidence
DROP POLICY IF EXISTS "select_evidence" ON evidence;
CREATE POLICY "select_evidence" ON evidence FOR SELECT
  TO authenticated USING (true);

-- Evidence: admins and investigators can upload evidence
DROP POLICY IF EXISTS "insert_evidence" ON evidence;
CREATE POLICY "insert_evidence" ON evidence FOR INSERT
  TO authenticated WITH CHECK (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role IN ('ADMIN', 'INVESTIGATOR'))
  );

-- Evidence: admins and investigators can update evidence (e.g., mark as parsed)
DROP POLICY IF EXISTS "update_evidence" ON evidence;
CREATE POLICY "update_evidence" ON evidence FOR UPDATE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role IN ('ADMIN', 'INVESTIGATOR'))
  ) WITH CHECK (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role IN ('ADMIN', 'INVESTIGATOR'))
  );

-- Evidence: only admins can delete evidence
DROP POLICY IF EXISTS "delete_evidence" ON evidence;
CREATE POLICY "delete_evidence" ON evidence FOR DELETE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'ADMIN')
  );

-- ============================================================
-- EVENTS TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  case_id uuid NOT NULL REFERENCES cases(id) ON DELETE CASCADE,
  evidence_id uuid REFERENCES evidence(id) ON DELETE SET NULL,
  timestamp timestamptz NOT NULL,
  event_type text NOT NULL CHECK (event_type IN (
    'LOGIN_FAILED', 'LOGIN_SUCCESS', 'LOGOUT',
    'FILE_ACCESS', 'FILE_MODIFY', 'FILE_DELETE',
    'NETWORK_CONNECTION', 'NETWORK_DNS', 'NETWORK_BLOCKED',
    'PRIVILEGE_ESCALATION', 'OTHER'
  )),
  username text,
  source_ip inet,
  destination_ip inet,
  source text,
  description text,
  severity text NOT NULL DEFAULT 'LOW' CHECK (severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
  raw_data jsonb
);

ALTER TABLE events ENABLE ROW LEVEL SECURITY;

-- Events: authenticated users can see all events
DROP POLICY IF EXISTS "select_events" ON events;
CREATE POLICY "select_events" ON events FOR SELECT
  TO authenticated USING (true);

-- Events: admins and investigators can insert events (from parsing)
DROP POLICY IF EXISTS "insert_events" ON events;
CREATE POLICY "insert_events" ON events FOR INSERT
  TO authenticated WITH CHECK (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role IN ('ADMIN', 'INVESTIGATOR'))
  );

-- Events: admins and investigators can update events
DROP POLICY IF EXISTS "update_events" ON events;
CREATE POLICY "update_events" ON events FOR UPDATE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role IN ('ADMIN', 'INVESTIGATOR'))
  ) WITH CHECK (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role IN ('ADMIN', 'INVESTIGATOR'))
  );

-- Events: only admins can delete events
DROP POLICY IF EXISTS "delete_events" ON events;
CREATE POLICY "delete_events" ON events FOR DELETE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'ADMIN')
  );

-- ============================================================
-- ALERTS TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS alerts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  case_id uuid NOT NULL REFERENCES cases(id) ON DELETE CASCADE,
  alert_type text NOT NULL,
  severity text NOT NULL DEFAULT 'MEDIUM' CHECK (severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
  confidence integer NOT NULL DEFAULT 0 CHECK (confidence >= 0 AND confidence <= 100),
  reason text NOT NULL,
  related_event_ids uuid[] DEFAULT '{}',
  detection_rule text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE alerts ENABLE ROW LEVEL SECURITY;

-- Alerts: authenticated users can see all alerts
DROP POLICY IF EXISTS "select_alerts" ON alerts;
CREATE POLICY "select_alerts" ON alerts FOR SELECT
  TO authenticated USING (true);

-- Alerts: admins and investigators can create alerts
DROP POLICY IF EXISTS "insert_alerts" ON alerts;
CREATE POLICY "insert_alerts" ON alerts FOR INSERT
  TO authenticated WITH CHECK (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role IN ('ADMIN', 'INVESTIGATOR'))
  );

-- Alerts: admins and investigators can update alerts
DROP POLICY IF EXISTS "update_alerts" ON alerts;
CREATE POLICY "update_alerts" ON alerts FOR UPDATE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role IN ('ADMIN', 'INVESTIGATOR'))
  ) WITH CHECK (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role IN ('ADMIN', 'INVESTIGATOR'))
  );

-- Alerts: only admins can delete alerts
DROP POLICY IF EXISTS "delete_alerts" ON alerts;
CREATE POLICY "delete_alerts" ON alerts FOR DELETE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'ADMIN')
  );

-- ============================================================
-- INDICATORS TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS indicators (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  case_id uuid NOT NULL REFERENCES cases(id) ON DELETE CASCADE,
  type text NOT NULL CHECK (type IN ('IP', 'USERNAME', 'FILENAME', 'DOMAIN', 'URL', 'HASH')),
  value text NOT NULL,
  description text,
  occurrence_count integer NOT NULL DEFAULT 1,
  risk_score integer CHECK (risk_score >= 0 AND risk_score <= 100)
);

ALTER TABLE indicators ENABLE ROW LEVEL SECURITY;

-- Indicators: authenticated users can see all indicators
DROP POLICY IF EXISTS "select_indicators" ON indicators;
CREATE POLICY "select_indicators" ON indicators FOR SELECT
  TO authenticated USING (true);

-- Indicators: admins and investigators can create indicators
DROP POLICY IF EXISTS "insert_indicators" ON indicators;
CREATE POLICY "insert_indicators" ON indicators FOR INSERT
  TO authenticated WITH CHECK (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role IN ('ADMIN', 'INVESTIGATOR'))
  );

-- Indicators: admins and investigators can update indicators
DROP POLICY IF EXISTS "update_indicators" ON indicators;
CREATE POLICY "update_indicators" ON indicators FOR UPDATE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role IN ('ADMIN', 'INVESTIGATOR'))
  ) WITH CHECK (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role IN ('ADMIN', 'INVESTIGATOR'))
  );

-- Indicators: only admins can delete indicators
DROP POLICY IF EXISTS "delete_indicators" ON indicators;
CREATE POLICY "delete_indicators" ON indicators FOR DELETE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'ADMIN')
  );

-- ============================================================
-- AUDIT LOGS TABLE
-- ============================================================
CREATE TABLE IF NOT EXISTS audit_logs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  action text NOT NULL,
  resource text,
  resource_id text,
  metadata jsonb,
  timestamp timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;

-- Audit logs: all authenticated users can read (investigators need to see activity)
DROP POLICY IF EXISTS "select_audit_logs" ON audit_logs;
CREATE POLICY "select_audit_logs" ON audit_logs FOR SELECT
  TO authenticated USING (true);

-- Audit logs: any authenticated user can insert (for logging their own actions)
DROP POLICY IF EXISTS "insert_audit_logs" ON audit_logs;
CREATE POLICY "insert_audit_logs" ON audit_logs FOR INSERT
  TO authenticated WITH CHECK (true);

-- Audit logs: no updates or deletes allowed (immutable log)
-- This is intentional — audit logs must never be modified after creation.

-- ============================================================
-- INDEXES
-- ============================================================

-- Cases: frequently filtered by status and risk_level
CREATE INDEX IF NOT EXISTS idx_cases_status ON cases(status);
CREATE INDEX IF NOT EXISTS idx_cases_risk_level ON cases(risk_level);
CREATE INDEX IF NOT EXISTS idx_cases_created_by ON cases(created_by);
CREATE INDEX IF NOT EXISTS idx_cases_created_at ON cases(created_at DESC);

-- Evidence: list by case
CREATE INDEX IF NOT EXISTS idx_evidence_case_id ON evidence(case_id);
CREATE INDEX IF NOT EXISTS idx_evidence_uploaded_at ON evidence(uploaded_at DESC);

-- Events: timeline queries (case + timestamp is the most common query)
CREATE INDEX IF NOT EXISTS idx_events_case_timestamp ON events(case_id, timestamp);
CREATE INDEX IF NOT EXISTS idx_events_case_type ON events(case_id, event_type);
CREATE INDEX IF NOT EXISTS idx_events_case_source_ip ON events(case_id, source_ip);
CREATE INDEX IF NOT EXISTS idx_events_case_severity ON events(case_id, severity);
CREATE INDEX IF NOT EXISTS idx_events_evidence_id ON events(evidence_id);

-- Alerts: sorted by severity and creation time
CREATE INDEX IF NOT EXISTS idx_alerts_case_severity ON alerts(case_id, severity);
CREATE INDEX IF NOT EXISTS idx_alerts_case_created_at ON alerts(case_id, created_at DESC);

-- Indicators: sorted by occurrence count
CREATE INDEX IF NOT EXISTS idx_indicators_case_id ON indicators(case_id);
CREATE INDEX IF NOT EXISTS idx_indicators_type_value ON indicators(type, value);

-- Audit logs: user activity history
CREATE INDEX IF NOT EXISTS idx_audit_logs_user_id ON audit_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_timestamp ON audit_logs(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_audit_logs_action ON audit_logs(action);

-- ============================================================
-- UPDATED_AT TRIGGER FOR CASES
-- ============================================================
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS cases_updated_at ON cases;
CREATE TRIGGER cases_updated_at
  BEFORE UPDATE ON cases
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();
